### ISSUE TITLE
Schema Feedback

### ISSUE THREAD

**Issue by edherm** [RyanGC93/fitnessOverflow#1]
Hello fitnessOverflow team!

I just finished looking over your schema. Please check out the feedback below, discuss, and let me know what questions or concerns you have.

## `Votes` Table
- [ ] Connecting this to both questions and answers is bonus. You should first focus on a votes table with just the `answerId` column. This particular combination of foreignKey columns will leave one or the other null. Making a foreignKey nullable can be tricky, so it is best left for later in the week when you are ready to tackle bonus features.
## `Comments` Table
- [ ] This is purely a bonus feature, so you don't really need to worry about this table for now. See above for an explanation of multiple foreignKeys and nullability.

**Comment by RyanGC93** [comment]
We resolved the schema for the database
